[workspace]
resolver = "2"
members = [
    "ipix-desktop/src-tauri",
    "ipix-rs",
    # "ipix-ios"
]
[patch.crates-io]
ipix-desktop = { path = "./ipix-desktop/src-tauri" }
ipix-rs = {path = "./ipix-rs"}
# ipix-ios = {path = "./ipix-ios"}

[profile.release]
strip = true 
lto = true
opt-level = "s"